### ISSUE TITLE
ImportError: cannot import name '__version__' from partially initialized module 'kuna'

### ISSUE THREAD

**Issue by dimadvk** [DmytroLitvinov/kuna#100]
* Kuna API wrapper version: 0.4.1
* Python version: 3.9.7
* Operating System: Linux Ubuntu 21.10

### Description

Exception "ImportError" is raised when I try to import KunaAPI class. 
There is a circular import that causes an issue. It was added in #99 

### What I Did
To reproduce just run the following:
```
pip install kuna
python -c 'from kuna import KunaAPI'
```

Execution result example:
```
$ pip install kuna
Collecting kuna
  Using cached kuna-0.4.1-py2.py3-none-any.whl
Requirement already satisfied: Click>=6.0 in ./.virtualenvs/tmp/lib/python3.9/site-packages (from kuna) (8.0.3)
Installing collected packages: kuna
Successfully installed kuna-0.4.1
$ 
$ python -c 'from kuna import KunaAPI'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dvk/.virtualenvs/tmp/lib/python3.9/site-packages/kuna/__init__.py", line 2, in <module>
    from .kuna import KunaAPI, APIError
  File "/home/dvk/.virtualenvs/tmp/lib/python3.9/site-packages/kuna/kuna.py", line 12, in <module>
    from kuna import __version__
ImportError: cannot import name '__version__' from partially initialized module 'kuna' (most likely due to a circular import) (/home/dvk/.virtualenvs/tmp/lib/python3.9/site-packages/kuna/__init__.py)

```

**Comment by DmytroLitvinov** [comment]
Hi @dimadvk ,
Version [0.4.2.](https://pypi.org/project/kuna/0.4.2/) was released.
Thank you for your contribution.
